baseurl = "/"
languageCode = "en-uk"
title = "Mitchell O'Hara-Wild"
theme = "AllinOne"
preserveTaxonomyNames = true
Paginate = 3
disqusShortname = "mitchell-blog"
googleAnalytics = "UA-120974019-1"
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyurls = true

builddrafts                = false
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = false
summaryLength              = 200

pygmentsuseclasses         = true


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  blog                     = "blog/:year-:month/:slug/"
  
[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

[params]
  faviconfile              = "img/main/icon.jpg"               # from static/
  avatar                   = "img/main/icon.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Mitchell O'Hara-Wild"
  description              = []           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "mail@mitchelloharawild.com"
  github                   = "//github.com/mitchelloharawild"
  linkedin                 = "//linkedin.com/in/mitchelloharawild"
  # facebook                 = "//facebook.com/you"
  # googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/mitchoharawild"
  # px500                    = "//px500"
  # instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon